apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  capacity:
    storage: 1Gi  # Adjust as necessary
  accessModes:
    - ReadWriteMany  # NFS supports this
  nfs:
    server: 172.31.17.152  # Your NFS server IP
    path: /mnt/nfs_share  # Path on your NFS server
